ENV["LC_ALL"] = "en_US.UTF-8"

$script = <<-EOF
export LC_ALL=en_US.UTF-8
sudo yum -y update
sudo yum -y install wget yum-utils
sudo rpm --import https://jenkins-ci.org/redhat/jenkins-ci.org.key
sudo wget -O /etc/yum.repos.d/jenkins.repo http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo
sudo wget -O /etc/yum.repos.d/nginx.repo https://raw.githubusercontent.com/artem-bondarenko/study/master/devops/lesson02/home-vm-jenkins/nginx.repo
sudo yum -y install jenkins nginx net-tools policycoreutils-python java
sudo wget -O /etc/sysconfig/jenkins https://raw.githubusercontent.com/artem-bondarenko/study/master/devops/lesson02/home-vm-jenkins/jenkins
sudo wget -O /etc/nginx/conf.d/default.conf https://raw.githubusercontent.com/artem-bondarenko/study/master/devops/lesson02/home-vm-jenkins/default.conf
sudo service jenkins start
sudo service nginx start
EOF

Vagrant.configure("2") do |config|
  config.vm.define "centos7-jenkins" do |jenkins|
    jenkins.vm.box = "centos/7"
    jenkins.vm.hostname = "jenkins.box"
    jenkins.vm.network "private_network", type: "dhcp"
    jenkins.vm.network "public_network", bridge: "wlp3s0", use_dhcp_assigned_default_route: true
    jenkins.vm.provision "shell", inline: $script
    jenkins.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.name = "centos7-jenkins"
      vb.cpus = 2
    end
  end
end

