ENV["LC_ALL"] = "en_US.UTF-8"

$script = <<-EOF
export LC_ALL=en_US.UTF-8
sudo yum -y update
sudo yum -y install wget yum-utils
sudo rpm --import https://jenkins-ci.org/redhat/jenkins-ci.org.key
sudo rpm --import https://nginx.org/keys/nginx_signing.key
sudo wget -O /etc/yum.repos.d/jenkins.repo http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo
sudo wget -O /etc/yum.repos.d/nginx.repo https://raw.githubusercontent.com/artem-bondarenko/study/master/devops/lesson02/home-vm-jenkins/nginx.repo
sudo yum -y install jenkins nginx net-tools policycoreutils-python java
sudo wget -O /etc/sysconfig/jenkins https://raw.githubusercontent.com/artem-bondarenko/study/master/devops/lesson02/home-vm-jenkins/jenkins
sudo wget -O /etc/nginx/conf.d/default.conf https://raw.githubusercontent.com/artem-bondarenko/study/master/devops/lesson02/home-vm-jenkins/default.conf
sudo timedatectl set-timezone Europe/Kiev
sudo setsebool -P httpd_can_network_connect on 
sudo systemctl start jenkins.service
sudo systemctl start nginx.service
sudo systemctl start firewalld.service
sudo firewall-cmd --permanent --service=jenkins --add-port=22222/tcp
sudo firewall-cmd --permanent --zone=public --remove-service=dhcpv6-client
sudo firewall-cmd --permanent --zone=public --add-service=http
sudo firewall-cmd --reload
sudo systemctl enable jenkins.service
sudo systemctl enable nginx.service
sudo systemctl enable firewalld.service
EOF

Vagrant.configure("2") do |config|
  config.vm.define "centos7-jenkins" do |jenkins|
    jenkins.vm.box = "centos/7"
    jenkins.vm.hostname = "jenkins.box"
    jenkins.vm.network "private_network", type: "dhcp"
    jenkins.vm.network "public_network", bridge: "wlp3s0", use_dhcp_assigned_default_route: true
    jenkins.vm.provision "shell", inline: $script
    jenkins.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.name = "centos7-jenkins"
      vb.cpus = 2
    end
  end
end

