---
- name: "Create user accounts"
  become: true
  user:
    name: "{{ item }}"
  with_items: "{{ users }}"
- name: "Add authorized keys"
  become: true
  authorized_key:
    user: "{{ item }}"
    key: "{{ lookup('file', '{{ role_path }}/files/' + item + '.pub') }}"
  with_items: "{{ users }}"
