ENV["LC_ALL"] = "en_US.UTF-8"

$scriptcentos = <<-CENTOSEOF
export LC_ALL=en_US.UTF-8
sudo yum -y update
sudo sestatus && sudo setenforce 0 && sudo sestatus
sudo yum -y install php httpd
CENTOSEOF

$scriptubuntu = <<-UBUNTUEOF
export LC_ALL=en_US.UTF-8
sudo apt update
UBUNTUEOF

Vagrant.configure("2") do |config|
  config.vm.define "centos7" do |centos|
	centos.vm.box = "centos/7"
	centos.vm.hostname = "centos.box"
	centos.vm.network :private_network, ip: "192.168.0.21"

	centos.vm.provision "shell", inline: $scriptcentos
  end

  config.vm.define "ubuntu1804" do |ubuntu|
	ubuntu.vm.box = "ubuntu/bionic64"
	ubuntu.vm.hostname = "ubuntu.box"
	ubuntu.vm.network :private_network, ip: "192.168.0.22"

	ubuntu.vm.provision "shell", inline: $scriptubuntu

  end
end
